package smarthouse.ejb.service;

import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:54:34.329+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://service.ejb.smarthouse/", name = "Authentication")
@XmlSeeAlso({ObjectFactory.class})
public interface Authentication {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.Ping")
    @WebMethod
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.PingResponse")
    public java.lang.String ping();
}
