
package smarthouse.ejb.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:54:34.294+01:00
 * Generated source version: 2.7.3
 * 
 */
public final class Authentication_AuthenticationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ejb.smarthouse/", "AuthenticationBeanService");

    private Authentication_AuthenticationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthenticationBeanService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuthenticationBeanService ss = new AuthenticationBeanService(wsdlURL, SERVICE_NAME);
        Authentication port = ss.getAuthenticationPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "";
        java.lang.String _login_arg1 = "";
        java.lang.String _login__return = port.login(_login_arg0, _login_arg1);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking ping...");
        java.lang.String _ping__return = port.ping();
        System.out.println("ping.result=" + _ping__return);


        }

        System.exit(0);
    }

}
