package smarthouse.ejb.service;

import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.xml.ws.WebEndpoint;
import org.jinouts.xml.ws.WebServiceClient;
import org.jinouts.xml.ws.WebServiceFeature;
import org.jinouts.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:54:34.338+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "AuthenticationBeanService", 
                  wsdlLocation = "http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/Authentication?wsdl",
                  targetNamespace = "http://service.ejb.smarthouse/") 
public class AuthenticationBeanService extends org.jinouts.ws.JinosService {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ejb.smarthouse/", "AuthenticationBeanService");
    public final static QName AuthenticationPort = new QName("http://service.ejb.smarthouse/", "AuthenticationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/Authentication?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthenticationBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/Authentication?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "AuthenticationPort")
    public Authentication getAuthenticationPort() {
        return super.getPort(AuthenticationPort, Authentication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "AuthenticationPort")
    public Authentication getAuthenticationPort(WebServiceFeature... features) {
        return super.getPort(AuthenticationPort, Authentication.class, features);
    }

}
