
package smarthouse.ejb.service;

import org.jinouts.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T17:27:10.995+01:00
 * Generated source version: 2.7.3
 */

@WebFault(name = "Exception", targetNamespace = "http://service.ejb.smarthouse/")
public class Exception_Exception extends java.lang.Exception {
    
    private smarthouse.ejb.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, smarthouse.ejb.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, smarthouse.ejb.service.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public smarthouse.ejb.service.Exception getFaultInfo() {
        return this.exception;
    }
}
