package smarthouse.ejb.service;

import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.xml.ws.WebEndpoint;
import org.jinouts.xml.ws.WebServiceClient;
import org.jinouts.xml.ws.WebServiceFeature;
import org.jinouts.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T10:54:19.181+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "HouseExplorerBeanService", 
                  wsdlLocation = "http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/HouseExplorer?wsdl",
                  targetNamespace = "http://service.ejb.smarthouse/") 
public class HouseExplorerBeanService extends org.jinouts.ws.JinosService {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ejb.smarthouse/", "HouseExplorerBeanService");
    public final static QName HouseExplorerPort = new QName("http://service.ejb.smarthouse/", "HouseExplorerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/HouseExplorer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HouseExplorerBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.214.56:8080/SmartHouseWeb-ejb-1.0.0/HouseExplorer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HouseExplorerBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HouseExplorerBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HouseExplorerBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HouseExplorer
     */
    @WebEndpoint(name = "HouseExplorerPort")
    public HouseExplorer getHouseExplorerPort() {
        return super.getPort(HouseExplorerPort, HouseExplorer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HouseExplorer
     */
    @WebEndpoint(name = "HouseExplorerPort")
    public HouseExplorer getHouseExplorerPort(WebServiceFeature... features) {
        return super.getPort(HouseExplorerPort, HouseExplorer.class, features);
    }

}
