package smarthouse.ejb.service;

import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T17:27:11.003+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://service.ejb.smarthouse/", name = "HousePilot")
@XmlSeeAlso({ObjectFactory.class})
public interface HousePilot {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "executeAction", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.ExecuteAction")
    @WebMethod
    @ResponseWrapper(localName = "executeActionResponse", targetNamespace = "http://service.ejb.smarthouse/", className = "smarthouse.ejb.service.ExecuteActionResponse")
    public smarthouse.ejb.service.ActionResponse executeAction(
        @WebParam(name = "arg0", targetNamespace = "")
        smarthouse.ejb.service.ActionRequest arg0
    ) throws Exception_Exception;
}
